# Generated by Django 3.1 on 2021-01-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('element_type', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(default='free', max_length=4)),
                ('owner_name', models.CharField(blank=True, max_length=10)),
                ('owner_number', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
