# Generated by Django 3.1 on 2021-01-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuelement',
            name='type',
        ),
    ]
