# Generated by Django 3.1 on 2021-01-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_remove_menuelement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
