# Generated by Django 3.1.5 on 2021-01-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_auto_20210126_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='place',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
