# Generated by Django 3.1.5 on 2021-01-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_auto_20210127_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
